# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('text', models.CharField(max_length=2000, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Raw Log',
                'verbose_name_plural': 'Raw Logs',
            },
        ),
    ]
