# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', editable=False, max_length=100, verbose_name='name')),
                ('count', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='count')),
                ('date_started', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='started')),
                ('date_finished', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='finished')),
                ('duration', models.DurationField(blank=True, db_index=True, default=None, null=True, verbose_name='duration')),
                ('log_text', models.TextField(blank=True, default=None, null=True, verbose_name='log')),
                ('error_text', models.TextField(blank=True, default=None, null=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'Worker Log',
                'verbose_name_plural': 'Worker Logs',
            },
        ),
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Mac Address',
                'verbose_name_plural': 'Mac Address',
            },
        ),
        migrations.CreateModel(
            name='RawLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('text', models.CharField(max_length=2000, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Raw Log',
                'verbose_name_plural': 'Raw Logs',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('action', models.CharField(choices=[('wlan-connect', 'connect wlan'), ('wlan-disconnect', 'disconnect wlan')], max_length=50, verbose_name='action')),
            ],
            options={
                'verbose_name': 'User Action',
                'verbose_name_plural': 'User Actions',
            },
        ),
    ]
