# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fritzlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', editable=False, max_length=100, verbose_name='name')),
                ('count', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='count')),
                ('date_started', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='started')),
                ('date_finished', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='finished')),
                ('duration', models.DurationField(blank=True, db_index=True, default=None, null=True, verbose_name='duration')),
                ('log_text', models.TextField(blank=True, default=None, null=True, verbose_name='log')),
                ('error_text', models.TextField(blank=True, default=None, null=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
