# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritzlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC')),
                ('speed', models.IntegerField(verbose_name='speed')),
                ('signal_strength', models.IntegerField(verbose_name='signal strength')),
            ],
            options={
                'verbose_name': 'Mac Address',
                'verbose_name_plural': 'Mac Address',
            },
        ),
    ]
