# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritzlog', '0003_auto_20171129_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('filename', models.CharField(max_length=50, verbose_name='filename')),
                ('size', models.BigIntegerField(verbose_name='filesize')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='is parsed')),
            ],
            options={
                'verbose_name': 'Capture',
                'verbose_name_plural': 'Captures',
            },
        ),
    ]
