# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritzlog', '0005_capture_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteddevice',
            name='ip',
            field=models.CharField(max_length=40, verbose_name='IP'),
        ),
    ]
