# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fritzlog', '0006_auto_20171129_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('query_name', models.CharField(max_length=200, verbose_name='query')),
                ('cname', models.CharField(blank=True, max_length=200, null=True, verbose_name='alias')),
            ],
            options={
                'verbose_name': 'DNS Response',
                'verbose_name_plural': 'DNS Responses',
            },
        ),
        migrations.CreateModel(
            name='GeoIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('asnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='asnum')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='lat')),
                ('lon', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='lon')),
            ],
            options={
                'verbose_name': 'GeoIP',
                'verbose_name_plural': 'GeoIPs',
            },
        ),
        migrations.CreateModel(
            name='NslookupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.CharField(max_length=40, verbose_name='IP')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='response')),
            ],
            options={
                'verbose_name': 'Nslookup Requests',
                'verbose_name_plural': 'Nslookup Requests',
            },
        ),
        migrations.CreateModel(
            name='WhoisRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.CharField(max_length=40, verbose_name='IP')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='response')),
            ],
            options={
                'verbose_name': 'Whois Requests',
                'verbose_name_plural': 'Whois Requests',
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='connections',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True, verbose_name='connections'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='ip',
            field=models.CharField(max_length=40, verbose_name='IP'),
        ),
    ]
