# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDbConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('host', models.CharField(max_length=256, verbose_name='hostname')),
                ('port', models.SmallIntegerField(verbose_name='port')),
                ('is_error', models.BooleanField(default=False, verbose_name='is error')),
                ('data', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True, verbose_name='tables')),
            ],
            options={
                'verbose_name': 'MongoDB Connection',
                'verbose_name_plural': 'MongoDB Connections',
            },
        ),
    ]
